import React from 'react';
import { Helmet } from 'react-helmet';
import caseStudy from '../../images/case_study_overview.jpg';

const CaseStudy1 = () => {
    return (
        <>
            <Helmet>
                <title>Case Study | Maximizing Leads with Account-Based Marketing</title>
                <meta name="description" content="Learn how Ni-Val helped Dell Technologies generate qualified leads through Account-Based Marketing." />
            </Helmet>

            {/* Hero Section */}
            <section className="case-study-hero">
                <div className="container">
                    <div className="row align-items-center hero-page">
                        <div className="col-md-8 col-lg-6">
                            <h1
                                className="hero-heading text-light"
                                data-aos="fade-up"
                                data-aos-duration="1200"
                                data-aos-delay="500"
                            >
                                Maximum Leads Generated By Using Account-Based Marketing
                            </h1>
                        </div>
                    </div>
                </div>
            </section>

            {/* Client Overview */}
            <section id="dell-client-overview" className="client-overview-section py-5">
                <div className="container">
                    <div className="row align-items-center">
                        {/* Client Image */}
                        <div className="col-md-6">
                            <img src={caseStudy} alt="case study" className="img-fluid mb-4 mb-md-0" />
                        </div>

                        {/* Client Overview Text */}
                        <div className="col-md-6">
                            <h2 className="section-heading">Client Overview:</h2>
                            <p className="section-content">Dell Technologies provides the essential infrastructure for organizations to build their digital future, IT and protect their most important asset, information.</p>
                            <p className='section-content'><strong className='strong-text'>Target Audience: </strong></p>
                            <ul className='section-content'>
                                <li><strong>Decision Makers:</strong> Senior Manager, Director, Head (IT Security)</li>
                                <li><strong>Profiling Criteria:</strong> Budget, Timeline, Security Challenges</li>
                                <li><strong>Industries:</strong> Retail, Manufacturing, Telecom, Food & Beverage</li>
                                <li><strong>Geography:</strong> US, UK, France, Germany, DACH, Australia, Singapore</li>
                            </ul>
                            <p className='section-content'><strong className='strong-text'>Challenges: </strong></p>
                            <p className="section-content">The Marketing team of Dell wanted to find decision makers from a TAL to boost their program. They had already secured leads from their team but were unable to penetrate many other accounts.</p>
                        </div>
                    </div>
                </div>
            </section>

            {/* Solution Section */}
            <section className="solution">
                <div className="container">
                    <div className="row align-items-center">
                        <div className="col-lg-10 purpose px-4 px-md-5 mb-4 mb-md-0 py-5">
                            <h2 className='pb-3 section-heading'>How We Helped Them</h2>
                            <p className='section-content'><strong className='strong-text'>Solution: </strong></p>
                            <p className='section-content'>Firstly, our database team gathered all business card details from our own database and secondary web research. This data was passed on to the team of telecallers to prospect and find leads in 470 accounts globally. Our multilingual team operates from one single delivery center, overcoming language barriers and maintaining coordination and consistency on the campaign. A complimentary whitepaper was sent out to all leads, and information on decision-making, budget, and timeline was captured over the call. Recordings were submitted along with the lead sheet for transparency and opt-in management.</p>
                            <p className='mb-0'><strong className='strong-text'>Results: </strong></p>
                            <ul className='section-content'>
                                <li>In 20 days (4-week program), our team secured 140 qualified leads amongst 470 accounts targeting Directors, Managers, and Heads of IT Security departments.</li>
                                <li><strong>Team Details:</strong> 2 Tele Callers, 1 Web Researcher</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </section>

            {/* Call to Action */}
            <section className="cta py-5 text-center" style={{ backgroundColor: '#9E8B5C', color: '#fff' }}>
                <div className="container">
                    <h2>Interested in a Similar Success?</h2>
                    <p>Contact us today to learn how we can help your business achieve growth through Account-Based Marketing.</p>
                    <a className='text-center section-button' href='/contact'><span>Contact Us</span></a>
                </div>
            </section>
        </>
    );
};

export default CaseStudy1;
