import React from 'react';
import { Link } from 'react-router-dom';
import HorizontalBarChart from './HorizontalBarChart';
import PieChartComponent from './PieChartComponent';
import DoughnutChart from './DoughnutChart';

const CaseStudy = () => {
    return (
        <main>
            <section className="case-study-hero">
                <div className="container">
                    <div className="row align-items-center hero-page">
                        <div className="col-md-8 col-lg-6">
                            <h1
                                className="hero-heading text-light"
                                data-aos="fade-up"
                                data-aos-duration="1200"
                                data-aos-delay="500"
                            >
                                Maximum Leads Generated By Using Account Based Marketing
                            </h1>
                        </div>
                    </div>
                </div>
            </section>
            <section className="campaign">
                <div className="contianer-fluid">
                    <div className="row alig-items-center ">
                        <div className="col-lg-5 purpose px-4 px-md-5 mb-4 mb-md-0 py-5">
                            <p className='section-content'><strong className='strong-text'>Purpose: </strong>Lead Generation</p>
                            <p className='section-content'><strong className='strong-text'>Requirement: </strong>One of the leading IT company in the USA wants to promote its services to the given TAL and personalize their approach to ABM.</p>
                            <p className='section-content mb-0'><strong className='strong-text'>Challenges: </strong></p>
                            <ul className='section-content'>
                                <li>Lack of accurate contacts in their target accounts</li>
                                <li>Sales was wasting valuable selling time ondeadendsand manual research.</li>
                                <li>Low match rates, lack of filters, and spotty directdial data.</li>
                            </ul>
                        </div>
                        <div className="col-lg-7 campaign-data py-5">
                            <h2 className='text-center pb-3 section-heading'>Campaign Specification</h2>
                            <div className="row">
                                <div className="col-md-6 ">
                                    <div className="profile-targeted mb-3 text-center">
                                        <p className='ms-3 mt-3 p-2 bg-primary text-white d-inline-block rounded-3'>Profile Targeted</p>
                                        <HorizontalBarChart />
                                    </div>
                                    <div className="geos-targetted mb-3 text-center">
                                        <p className='ms-3 mt-3 p-2 bg-primary text-white d-inline-block rounded-3'>Geo Targeted</p>
                                        <PieChartComponent />
                                    </div>
                                </div>
                                <div className="col-md-6 d-flex flex-column align-self-stretch justify-content-between">
                                    <div className="sectors mb-3 text-center">
                                        <p className='ms-3 mt-3 p-2 bg-primary text-white d-inline-block rounded-3'>Profile Targeted</p>
                                        <span className='campain-count fs-1 d-block'>360</span>
                                        <p>Degree Sectors</p>
                                    </div>
                                    <div className="emp-size mb-3 text-center">
                                        <p className='ms-3 mt-3 p-2 bg-primary text-white d-inline-block rounded-3'>Employee Size</p>
                                        <span className='campain-count fs-1 d-block'>10 - 10,000+</span>
                                    </div>
                                    <div className="revenue mb-3 text-center">
                                        <p className='ms-3 mt-3 p-2 bg-primary text-white d-inline-block rounded-3'>Revenue</p>
                                        <span className='campain-count fs-1 d-block'>1M</span>
                                        <p>USD and above</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <section className="campaign">
                <div className="contianer-fluid">
                    <div className="row alig-items-center ">
                        <div className="col-lg-5 campaign-data py-5">
                            <h2 className='text-center section-heading'>Key Takeaways</h2>
                            <div className="profile-targeted mb-3 text-center">
                                <DoughnutChart />
                                <div>
                                    <ul className='mt-4 text-start'>
                                        <li>20% of leads generated through Telephonic Call on quarterly bases.</li>
                                        <li>60% of leads generated through Email marketing on quarterly bases.</li>
                                        <li>20% Leads generated through Digital Ads on quarterly bases.</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div className="col-lg-7 purpose px-4 px-md-5 mb-4 mb-md-0 py-5">
                            <h2 className=' pb-3 section-heading'>How we helped them?</h2>
                            <p className='section-content'>For this lead generation campaign, an account based marketing strategy was created for targeted companies list provided by the client. The most efficient channels to reach the customers were selected. So, we decided to generate the leads via telephonic, email, and linkedInad campaign methods. Our database team fetched out the data for the telemarketing team as well as for the email marketing team. The script and banner was designed for telemarketing team and for running linkedInand email campaign</p>
                            <p className='section-content'>One of the leading IT company in the USA wants to promote its services to the given TAL and personalize their approach to ABM.•With this approach we where able to reach and 60% of leads generated through Email marketing on quarterly bases. 20% Leads generated through Digital Ads on quarterly bases. Telephonic Digital Marketing influence the niche target group, and clear value propositions were created for each buyer persona.
                            </p>
                            <p className='mb-0'><strong className='strong-text'>Challenges: </strong></p>
                            <ul className='section-content'>
                                <li>Lack of accurate contacts in their target accounts</li>
                                <li>Sales was wasting valuable selling time ondeadendsand manual research.</li>
                                <li>Low match rates, lack of filters, and spotty directdial data.</li>
                            </ul>
                            <p className='mb-0'><strong className='strong-text'>Methodology: </strong></p>
                            <div className="container">
                                <div className="row methodology">
                                    <div className="col-4 text-center">
                                        <i className="fa-solid fa-phone-volume"></i>
                                        <p className="section-content">Telephonic</p>
                                    </div>
                                    <div className="col-4 text-center">
                                        <i class="fa fa-envelope"></i>
                                        <p className="section-content">Email Marketing</p>
                                    </div>
                                    <div className="col-4 text-center">
                                        <i class="fa-solid fa-rectangle-ad"></i>
                                        <p className="section-content">Digital Marketing</p>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </section>
            <section className="case-studies py-5">
                <div className="container">
                    <h1 className="text-center mb-4">Our Case Studies</h1>
                    <div className="row">
                        {/* IBM Case Study */}
                        <div className="col-md-6 mb-4">
                            <div className="card">
                                <div className="card-body">
                                    <h3>IBM Case Study</h3>
                                    <p>Learn how IBM generated 4,100 MQLs during a 3-month content syndication program.</p>
                                    <Link to="/case-study/ibm" className="btn btn-primary">Read More</Link>
                                </div>
                            </div>
                        </div>
                        {/* Dell Case Study */}
                        <div className="col-md-6 mb-4">
                            <div className="card">
                                <div className="card-body">
                                    <h3>Dell Technologies Case Study</h3>
                                    <p>Discover how Dell secured 140 qualified leads in 20 days with Account-Based Marketing.</p>
                                    <Link to="/case-study/dell" className="btn btn-primary">Read More</Link>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </main>
    );
};

export default CaseStudy;
