import React, { useEffect } from 'react';
import { Helmet } from 'react-helmet';
import AOS from 'aos';
import 'aos/dist/aos.css';
import caseStudy from '../../images/case_study_overview.jpg';

const CaseStudy2 = () => {
    // Initialize AOS for animations
    useEffect(() => {
        AOS.init({
            duration: 1000,
            once: true,  // Only animate once
        });
    }, []);

    return (
        <>
            <Helmet>
                <title>Case Study | Maximizing Leads with Account-Based Marketing</title>
                <meta name="description" content="Learn how Ni-Val helped IBM generate 4,100 MQLs through Account-Based Marketing and drive engagement in an omnichannel way." />
                <meta name="keywords" content="IBM Case Study, Lead Generation, MQL, Account-Based Marketing, Cloud Solutions" />
                <link rel="canonical" href="https://www.ni-val.com/case-study/ibm" />
            </Helmet>

            {/* Hero Section */}
            <section className="case-study-hero" data-aos="fade-up">
                <div className="container">
                    <div className="row align-items-center hero-page">
                        <div className="col-md-8 col-lg-6">
                            <h1 className="hero-heading text-light">
                                Maximum Leads Generated By Using Account-Based Marketing
                            </h1>
                        </div>
                    </div>
                </div>
            </section>

            {/* Client Overview Section */}
            <section id="ibm-client-overview" className="client-overview-section py-5">
                <div className="container" data-aos="fade-right">
                    <div className="row align-items-center">
                        {/* Client Image */}
                        <div className="col-md-6">
                            <img src={caseStudy} alt="IBM Case Study" className="img-fluid mb-4 mb-md-0" />
                        </div>

                        {/* Client Overview Text */}
                        <div className="col-md-6" data-aos="fade-left">
                            <h2 className="section-heading">Client Overview:</h2>
                            <p className="section-content">IBM is a leading cloud platform and cognitive solutions company, and is listed among the Fortune 500.</p>
                            <p className='section-content'><strong className='strong-text'>Target Audience: </strong></p>
                            <ul className='section-content'>
                                <li><strong>Decision Makers:</strong> IT Manager, Network Admin, VP, Director</li>
                                <li><strong>Profiling Criteria:</strong> All, except Govt. & Public sector</li>
                                <li><strong>Industries:</strong> All, except Govt. & Public sector</li>
                                <li><strong>Geography:</strong> US, Canada, Middle East, South Africa, BENELUX, India, Australia, New Zealand</li>
                            </ul>
                            <p className='section-content'><strong className='strong-text'>Challenges: </strong></p>
                            <p className="section-content">For a company of IBM's scale, it’s crucial to generate fresh leads regularly, engage customers, and keep prospects updated with their latest offerings. IBM relies on agencies like Ni-Val to drive engagement in an omnichannel way. The challenge was to obtain opt-in data and profile opportunities in the European market.</p>
                        </div>
                    </div>
                </div>
            </section>

            {/* Solution Section */}
            <section className="solution py-5">
                <div className="container" data-aos="fade-up">
                    <div className="row align-items-center">
                        <div className="col-lg-10 purpose px-4 px-md-5 mb-4 mb-md-0">
                            <h2 className='pb-3 section-heading'>How We Helped Them</h2>
                            <p className='section-content'><strong className='strong-text'>Solution: </strong></p>
                            <p className='section-content'>Content syndication and MQL generation through telemarketing and email marketing. A comprehensive program was designed to disseminate their latest whitepaper on network infrastructure solutions and obtain permission for future marketing initiatives. The program, conducted over three months, included both email marketing campaigns and a team of telecallers to reach maximum prospects.</p>
                            <p className='mb-0'><strong className='strong-text'>Results: </strong></p>
                            <ul className='section-content'>
                                <li>We delivered 4,100 MQLs during the 3-month program. 160k people engaged with the content, and IBM saw a notable increase in online traffic.</li>
                                <li><strong>Team Details:</strong> 12 Tele Callers and 3 Email Marketing Specialists.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </section>

            {/* Call to Action Section */}
            <section className="cta py-5 text-center" style={{ backgroundColor: '#9E8B5C', color: '#fff' }} data-aos="fade-up">
                <div className="container">
                    <h2>Interested in a Similar Success?</h2>
                    <p>Contact us today to learn how we can help your business achieve growth through Account-Based Marketing.</p>
                    <a className='text-center section-button' href='/contact'><span>Contact Us</span></a>
                </div>
            </section>
        </>
    );
};

export default CaseStudy2;
