import { Helmet } from 'react-helmet';
import 'aos/dist/aos.css';
import HorizontalBarChart from './HorizontalBarChart';
import PieChartComponent from './PieChartComponent';
import DoughnutChart from './DoughnutChart';

const CaseStudy = () => {

    return (
        <>
            {/* Helmet for SEO */}
            <Helmet>
                <title>Case Study | Account-Based Marketing</title>
                <meta
                    name="description"
                    content="Learn how Ni-Val helped generate maximum leads using Account-Based Marketing strategies. Discover the challenges, solutions, and results."
                />
            </Helmet>

            <main>
                {/* Hero Section */}
                <section className="case-study-hero" data-aos="fade-up">
                    <div className="container">
                        <div className="row align-items-center hero-page">
                            <div className="col-md-8 col-lg-6">
                                <h1 className="hero-heading text-light" data-aos="fade-up">
                                    Maximum Leads Generated By Using Account-Based Marketing
                                </h1>
                            </div>
                        </div>
                    </div>
                </section>

                {/* Campaign Section */}
                <section className="campaign" data-aos="fade-up">
                    <div className="container">
                        <div className="row align-items-center">
                            <div className="col-lg-5 purpose px-4 px-md-5 mb-4 mb-md-0 py-5" data-aos="fade-right">
                                <p className='section-content'><strong className='strong-text'>Purpose: </strong>Lead Generation</p>
                                <p className='section-content'><strong className='strong-text'>Requirement: </strong>One of the leading IT companies in the USA wanted to promote its services to the given TAL and personalize their approach to ABM.</p>
                                <p className='section-content mb-0'><strong className='strong-text'>Challenges: </strong></p>
                                <ul className='section-content'>
                                    <li>Lack of accurate contacts in their target accounts</li>
                                    <li>Sales was wasting valuable selling time on dead-ends and manual research.</li>
                                    <li>Low match rates, lack of filters, and spotty direct-dial data.</li>
                                </ul>
                            </div>

                            <div className="col-lg-7 campaign-data py-5" data-aos="fade-left">
                                <h2 className='text-center pb-3 section-heading'>Campaign Specification</h2>
                                <div className="row">
                                    <div className="col-md-6">
                                        <div className="profile-targeted mb-3 text-center">
                                            <p className='ms-3 mt-3 p-2 bg-primary text-white d-inline-block rounded-3'>Profile Targeted</p>
                                            <HorizontalBarChart />
                                        </div>
                                        <div className="geos-targeted mb-3 text-center">
                                            <p className='ms-3 mt-3 p-2 bg-primary text-white d-inline-block rounded-3'>Geo Targeted</p>
                                            <PieChartComponent />
                                        </div>
                                    </div>

                                    <div className="col-md-6 d-flex flex-column justify-content-between">
                                        <div className="sectors mb-3 text-center" data-aos="fade-up">
                                            <p className='ms-3 mt-3 p-2 bg-primary text-white d-inline-block rounded-3'>Profile Targeted</p>
                                            <span className='campaign-count fs-1 d-block'>360</span>
                                            <p>Degree Sectors</p>
                                        </div>
                                        <div className="emp-size mb-3 text-center" data-aos="fade-up">
                                            <p className='ms-3 mt-3 p-2 bg-primary text-white d-inline-block rounded-3'>Employee Size</p>
                                            <span className='campaign-count fs-1 d-block'>10 - 10,000+</span>
                                        </div>
                                        <div className="revenue mb-3 text-center" data-aos="fade-up">
                                            <p className='ms-3 mt-3 p-2 bg-primary text-white d-inline-block rounded-3'>Revenue</p>
                                            <span className='campaign-count fs-1 d-block'>1M</span>
                                            <p>USD and above</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

                {/* Key Takeaways Section */}
                <section className="campaign" data-aos="fade-up">
                    <div className="container">
                        <div className="row align-items-center">
                            <div className="col-lg-5 campaign-data py-5">
                                <h2 className='text-center section-heading'>Key Takeaways</h2>
                                <div className="profile-targeted mb-3 text-center" data-aos="zoom-in">
                                    <DoughnutChart />
                                    <div>
                                        <ul className='mt-4 text-start'>
                                            <li>20% of leads generated through Telephonic Calls on a quarterly basis.</li>
                                            <li>60% of leads generated through Email marketing on a quarterly basis.</li>
                                            <li>20% of leads generated through Digital Ads on a quarterly basis.</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div className="col-lg-7 purpose px-4 px-md-5 mb-4 mb-md-0 py-5">
                                <h2 className='pb-3 section-heading' data-aos="fade-left">How We Helped Them</h2>
                                <p className='section-content'>
                                    For this lead generation campaign, an account-based marketing strategy was created for the targeted companies provided by the client. The most efficient channels to reach the customers were selected, including telephonic, email, and LinkedIn ad campaign methods.
                                </p>
                                <p className='section-content'>
                                    Our database team gathered data for the telemarketing and email marketing teams. Scripts and banners were designed for telemarketing and for running LinkedIn and email campaigns. With this approach, we reached and influenced the niche target group, creating clear value propositions for each buyer persona.
                                </p>
                            </div>
                        </div>
                    </div>
                </section>

                {/* Related Case Studies Section */}
                <section className="service-details case-study-block" data-aos="fade-up">
                    <div className="container py-5">
                        <h1 className="text-center mb-4">Our Case Studies</h1>
                        <div className="row justify-content-center">
                            <div className="col-md-6 col-lg-4 service-box" data-aos="fade-up">
                                <div className="service text-center p-4 h-100">
                                    <div className="service-content">
                                        <h2 className="service-head fs-4">IBM Case Study</h2>
                                        <p className="service-description">Learn how IBM generated 4,100 MQLs during a 3-month content syndication program.</p>
                                        <a href='/case-study/ibm' className="btn btn-secondary mt-3 text-white">Read More</a>
                                    </div>
                                </div>
                            </div>
                            <div className="col-md-6 col-lg-4 service-box" data-aos="fade-up">
                                <div className="service text-center p-4 h-100">
                                    <div className="service-content">
                                        <h2 className="service-head fs-4">Dell Technologies Case Study</h2>
                                        <p className="service-description">Discover how Dell secured 140 qualified leads in 20 days with Account-Based Marketing.</p>
                                        <a href='/case-study/dell' className="btn btn-secondary mt-3 text-white">Read More</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </main>
        </>
    );
};

export default CaseStudy;
